import React, { useState } from "react";
import { auditDocumentText, auditUploadedFile } from "../api";

const SAMPLE_DOCS = [
  {
    label: "🚀 Artemis II Press Briefing",
    title: "NASA Artemis II Crew and SLS Mission Announcement",
    text: `NASA announced the four astronauts who will fly around the Moon on Artemis II: Reid Wiseman, Victor Glover, Christina Koch, and Jeremy Hansen. The 10-day flight test will pave the way for human missions to the lunar surface. The mission relies on NASA's Space Launch System (SLS) rocket and Orion spacecraft. NASA stated that Artemis II will test vital life-support systems in deep space. Furthermore, the spacecraft will travel approximately 5,700 nautical miles beyond the far side of the Moon before returning to Earth with a splashdown in the Pacific Ocean.`
  },
  {
    label: "📈 Trent Retail Statement",
    title: "Trent Limited Q2 Financial and Expansion Filing",
    text: `Tata Group's retail firm Trent Limited reported a 23% year-on-year rise in standalone revenue for the July-September 2026 quarter. Operating revenue was driven by sustained expansion of its Zudio and Westside apparel stores. The company opened several new stores across tier-2 and tier-3 Indian cities during the quarter. Management confirmed that sales grew steadily despite competitive pressures in the fast-fashion segment.`
  },
  {
    label: "🦠 5G Wireless & Health Claims",
    title: "Viral Report: 5G Millimeter Wave Radiation",
    text: `Controversial online claims allege that 5G millimeter wave cell towers emit hazardous radiation that transmits viral pathogens and causes respiratory illness. The report suggests that high-frequency electromagnetic radiation directly creates coronavirus pathogens in human cells and causes widespread immune system suppression.`
  }
];

const DocumentAuditView = () => {
  const [docTitle, setDocTitle] = useState("");
  const [docText, setDocText] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [auditResult, setAuditResult] = useState(null);

  const handleSelectSample = (sample) => {
    setDocTitle(sample.title);
    setDocText(sample.text);
    setSelectedFile(null);
    setError("");
    setAuditResult(null);
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedFile(file);
      setDocTitle(file.name.replace(/\.[^/.]+$/, ""));
      setError("");
    }
  };

  const handleClear = () => {
    setDocTitle("");
    setDocText("");
    setSelectedFile(null);
    setError("");
    setAuditResult(null);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    if (!selectedFile && (!docText || docText.trim().length < 30)) {
      setError("Please provide an article of at least 30 characters, or upload a document file (.pdf, .txt).");
      return;
    }

    setIsLoading(true);
    setAuditResult(null);

    try {
      let data;
      if (selectedFile) {
        data = await auditUploadedFile(selectedFile);
      } else {
        data = await auditDocumentText(docTitle.trim(), docText.trim());
      }
      setAuditResult(data);
    } catch (err) {
      setError(err.message || "Failed to complete document audit.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadAuditReport = () => {
    if (!auditResult) return;
    const { document_title, authenticity_score, overall_status, executive_assessment, word_count, audited_claims } = auditResult;

    let md = `# 📑 TruthLens AI — Document Authenticity Audit\n\n`;
    md += `**Document Title:** ${document_title}\n`;
    md += `**Authenticity Score:** ${authenticity_score}%\n`;
    md += `**Overall Credibility:** ${overall_status}\n`;
    md += `**Word Count:** ${word_count} words\n`;
    md += `**Audit Date:** ${new Date().toLocaleString()}\n\n`;
    md += `## Executive Assessment\n${executive_assessment}\n\n`;

    md += `## Fact-Checked Assertions (${audited_claims.length})\n\n`;
    audited_claims.forEach((c, idx) => {
      md += `### Assertion #${idx + 1}: "${c.text}"\n`;
      md += `- **Verdict:** ${c.verdict}\n`;
      md += `- **Reasoning:** ${c.reasoning}\n`;
      if (c.top_sources && c.top_sources.length > 0) {
        md += `- **Sources:** ${c.top_sources.join(", ")}\n`;
      }
      md += `\n`;
    });

    md += `---\n*Audit generated by TruthLens AI Document Intelligence Engine.*\n`;

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Document-Audit-${document_title.replace(/\s+/g, "_")}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getStatusBadgeClass = (status) => {
    switch (status) {
      case "HIGH_CREDIBILITY":
        return "status-high-credibility";
      case "MIXED_CREDIBILITY":
        return "status-mixed-credibility";
      case "HIGH_RISK":
      default:
        return "status-high-risk";
    }
  };

  const getStatusLabel = (status) => {
    switch (status) {
      case "HIGH_CREDIBILITY":
        return "✅ High Credibility";
      case "MIXED_CREDIBILITY":
        return "⚠️ Mixed Credibility";
      case "HIGH_RISK":
      default:
        return "❌ High Risk / Discrepancies Found";
    }
  };

  return (
    <div className="doc-audit-viewport">
      <div className="doc-audit-header">
        <span className="doc-audit-pill">Document Intelligence</span>
        <h1 className="doc-audit-title">Deep Document Authenticity Audit</h1>
        <p className="doc-audit-desc">
          Upload news PDFs, long-form articles, or press releases. TruthLens AI automatically decomposes key factual assertions and audits each claim against live journalism.
        </p>
      </div>

      <div className="doc-audit-card">
        {/* Sample Presets */}
        <div className="presets-container">
          <span className="presets-label">⚡ Try Sample Documents:</span>
          <div className="presets-grid">
            {SAMPLE_DOCS.map((sample, idx) => (
              <button
                key={idx}
                type="button"
                className="preset-chip-btn"
                onClick={() => handleSelectSample(sample)}
                disabled={isLoading}
              >
                {sample.label}
              </button>
            ))}
          </div>
        </div>

        <form onSubmit={handleSubmit} className="doc-audit-form">
          {/* File Upload Zone */}
          <div className="file-drop-zone">
            <input
              type="file"
              id="file-upload"
              className="file-input-hidden"
              accept=".pdf,.txt,.md"
              onChange={handleFileChange}
              disabled={isLoading}
            />
            <label htmlFor="file-upload" className="file-drop-label">
              <span className="drop-icon">📑</span>
              <div className="drop-text-group">
                <span className="drop-main-text">
                  {selectedFile ? `Selected: ${selectedFile.name}` : "Click to upload PDF (.pdf) or Text Document (.txt, .md)"}
                </span>
                <span className="drop-sub-text">Up to 20 pages • Automatic text extraction & multi-claim audit</span>
              </div>
            </label>
            {selectedFile && (
              <button
                type="button"
                className="remove-file-btn"
                onClick={() => setSelectedFile(null)}
                disabled={isLoading}
              >
                ✕ Remove File
              </button>
            )}
          </div>

          <div className="form-divider">
            <span>OR PASTE DOCUMENT CONTENT</span>
          </div>

          {/* Document Title (Optional) */}
          <div className="form-group">
            <label htmlFor="doc-title-input" className="form-label">
              Document Title <span className="label-optional">(Optional)</span>
            </label>
            <input
              id="doc-title-input"
              type="text"
              className="form-input"
              placeholder="e.g., Financial Report Q2, NASA Press Release..."
              value={docTitle}
              onChange={(e) => setDocTitle(e.target.value)}
              disabled={isLoading}
            />
          </div>

          {/* Long Content Textarea */}
          <div className="form-group">
            <div className="form-label-row">
              <label htmlFor="doc-content-input" className="form-label">
                Document Body Text <span className="label-required">*</span>
              </label>
              <span className="char-count">
                {docText.length} chars {docText.length > 0 && docText.length < 30 ? "(min 30 chars)" : ""}
              </span>
            </div>
            <textarea
              id="doc-content-input"
              className="form-textarea"
              rows={7}
              placeholder="Paste complete article text, research report, or statement here..."
              value={docText}
              onChange={(e) => setDocText(e.target.value)}
              disabled={isLoading || !!selectedFile}
            />
          </div>

          {error && (
            <div className="validation-alert" role="alert">
              ⚠️ {error}
            </div>
          )}

          <div className="form-actions">
            <button
              type="submit"
              className={`submit-button ${isLoading ? "loading" : ""}`}
              disabled={isLoading || (!selectedFile && !docText.trim())}
            >
              {isLoading ? (
                <>
                  <span className="spinner"></span>
                  <span>Auditing Document with AI...</span>
                </>
              ) : (
                "🔍 Run Document Audit"
              )}
            </button>

            {(docText || docTitle || selectedFile) && !isLoading && (
              <button
                type="button"
                className="clear-button"
                onClick={handleClear}
                disabled={isLoading}
              >
                Clear
              </button>
            )}
          </div>
        </form>
      </div>

      {/* Loading state indicator */}
      {isLoading && (
        <div className="doc-audit-loading-card">
          <div className="loading-orbit-spinner"></div>
          <div>
            <h3 className="loading-header-title">Extracting Claims & Auditing Document</h3>
            <p className="loading-header-subtitle">
              Decomposing assertions, executing concurrent live web searches, and cross-referencing facts...
            </p>
          </div>
        </div>
      )}

      {/* Audit Results View */}
      {auditResult && (
        <div className="audit-results-container">
          {/* Hero Score Card */}
          <div className={`audit-hero-card ${getStatusBadgeClass(auditResult.overall_status)}`}>
            <div className="audit-hero-top">
              <div>
                <span className={`audit-status-badge ${getStatusBadgeClass(auditResult.overall_status)}`}>
                  {getStatusLabel(auditResult.overall_status)}
                </span>
                <h2 className="audit-document-title">{auditResult.document_title}</h2>
                <div className="audit-meta-row">
                  <span>📄 {auditResult.word_count} Words</span>
                  <span>🎯 {auditResult.total_claims_detected} Key Claims Audited</span>
                  {auditResult.filename && <span>📎 {auditResult.filename}</span>}
                </div>
              </div>

              {/* Score Gauge */}
              <div className="audit-score-gauge">
                <div className="score-number">{auditResult.authenticity_score}%</div>
                <div className="score-label">Authenticity Score</div>
              </div>
            </div>

            <p className="audit-executive-text">{auditResult.executive_assessment}</p>

            {/* Claims Breakdown Pills */}
            <div className="audit-breakdown-strip">
              <span className="breakdown-pill sup">
                ✓ {auditResult.claims_breakdown.supported || 0} Supported
              </span>
              <span className="breakdown-pill con">
                ✗ {auditResult.claims_breakdown.contradicted || 0} Contradicted
              </span>
              <span className="breakdown-pill mis">
                ⚠️ {auditResult.claims_breakdown.misleading || 0} Misleading
              </span>
              <span className="breakdown-pill unv">
                ❓ {auditResult.claims_breakdown.unverified || 0} Unverified
              </span>
            </div>

            <div className="audit-hero-footer">
              <button
                type="button"
                className="audit-export-btn"
                onClick={handleDownloadAuditReport}
              >
                📝 Download Audit Dossier (.md)
              </button>
              <button
                type="button"
                className="audit-export-btn"
                onClick={() => window.print()}
              >
                📄 Print / Export PDF
              </button>
            </div>
          </div>

          {/* Claims List Table/Cards */}
          <div className="audited-claims-section">
            <h3 className="audited-claims-title">Fact-Checked Assertions Breakdown</h3>
            <div className="audited-claims-grid">
              {auditResult.audited_claims.map((claim, idx) => (
                <div key={claim.claim_id || idx} className="audited-claim-card">
                  <div className="claim-card-top">
                    <span className="claim-index-tag">Assertion #{idx + 1}</span>
                    <span className={`claim-verdict-tag verdict-${claim.verdict.toLowerCase()}`}>
                      {claim.verdict}
                    </span>
                  </div>

                  <p className="claim-statement">"{claim.text}"</p>

                  <div className="claim-reasoning-box">
                    <span className="reasoning-tag">AI Analysis:</span>
                    <p className="reasoning-body">{claim.reasoning}</p>
                  </div>

                  {claim.top_sources && claim.top_sources.length > 0 && (
                    <div className="claim-sources-row">
                      <span className="sources-label">Cited Outlets:</span>
                      <div className="sources-chips">
                        {claim.top_sources.map((src, i) => (
                          <span key={i} className="source-chip">{src}</span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DocumentAuditView;
